standardValueSetNames: [
  "AccountContactMultiRoles",
  "AccountContactRole",
  "AccountOwnership",
  "AccountRating",
  "AccountType",
  "AssetActionCategory",
  "AssetRelationshipType",
  "AssetStatus",
  "AssociatedLocationType",
  "CampaignMemberStatus",
  "CampaignStatus",
  "CampaignType",
  "CardType",
  "CareItemStatus",
  "CaseContactRole",
  "CaseOrigin",
  "CasePriority",
  "CaseReason",
  "CaseStatus",
  "CaseType",
  "ChangeRequestRelatedItemImpactLevel",
  "ChangeRequestBusinessReason",
  "ChangeRequestCategory",
  "ChangeRequestImpact",
  "ChangeRequestPriority",
  "ChangeRequestRiskLevel",
  "ChangeRequestStatus",
  "ContactPointAddressType",
  "ContactPointUsageType",
  "ContactRequestReason",
  "ContactRequestStatus",
  "ContactRole",
  "ContractContactRole",
  "ContractStatus",
  "ConsequenceOfFailure",
  "DigitalAssetStatus",
  "EntitlementType",
  "EventSubject",
  "EventType",
  "FinanceEventAction",
  "FinanceEventType",
  "FiscalYearPeriodName",
  "FiscalYearPeriodPrefix",
  "FiscalYearQuarterName",
  "FiscalYearQuarterPrefix",
  "ForecastingItemCategory",
  "FulfillmentStatus",
  "FulfillmentType",
  "IdeaCategory",
  "IdeaMultiCategory",
  "IdeaStatus",
  "IdeaThemeStatus",
  "IncidentCategory",
  "IncidentImpact",
  "IncidentPriority",
  "IncidentRelatedItemImpactLevel",
  "IncidentRelatedItemImpactType",
  "IncidentReportedMethod",
  "IncidentStatus",
  "IncidentSubCategory",
  "IncidentType",
  "IncidentUrgency",
  "Industry",
  "LeadSource",
  "LeadStatus",
  "LocationType",
  "MilitaryService",
  "OpportunityCompetitor",
  "OpportunityStage",
  "OpportunityType",
  "OrderItemSummaryChgRsn",
  "OrderStatus",
  "OrderSummaryRoutingSchdRsn",
  "OrderSummaryStatus",
  "OrderType",
  "PartnerRole",
  "ProblemCategory",
  "ProblemImpact",
  "ProblemPriority",
  "ProblemRelatedItemImpactLevel",
  "ProblemRelatedItemImpactType",
  "ProblemStatus",
  "ProblemSubCategory",
  "ProblemUrgency",
  "ProcessExceptionCategory",
  "ProcessExceptionPriority",
  "ProcessExceptionSeverity",
  "ProcessExceptionStatus",
  "Product2Family",
  "QuantityUnitOfMeasure",
  "QuestionOrigin",
  "QuickTextCategory",
  "QuickTextChannel",
  "QuoteStatus",
  "RoleInTerritory2",
  "ResourceAbsenceType",
  "ReturnOrderLineItemProcessPlan",
  "ReturnOrderLineItemReasonForRejection",
  "ReturnOrderLineItemReasonForReturn",
  "ReturnOrderLineItemRepaymentMethod",
  "ReturnOrderShipmentType",
  "ReturnOrderStatus",
  "SalesTeamRole",
  "Salutation",
  "ScorecardMetricCategory",
  "ServiceAppointmentStatus",
  "ServiceContractApprovalStatus",
  "ServTerrMemRoleType",
  "ShiftStatus",
  "SocialPostClassification",
  "SocialPostEngagementLevel",
  "SocialPostReviewedStatus",
  "SolutionStatus",
  "StatusReason",
  "TaskPriority",
  "TaskStatus",
  "TaskSubject",
  "TaskType",
  "UnitOfMeasure",
  "WorkOrderLineItemPriority",
  "WorkOrderLineItemStatus",
  "WorkOrderPriority",
  "WorkOrderStatus",
  "WorkStepStatus",
  "WorkTypeDefApptType",
  "WorkTypeGroupAddInfo",
]
